# Generated by Django 4.1.4 on 2023-04-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_book_book_date_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.room', verbose_name='会议室名称'),
        ),
    ]
