# Generated by Django 4.1.4 on 2023-04-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_book_book_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.IntegerField(choices=[(1, '8:00-9:00'), (2, '9:00-10:00'), (3, '10:00-11:00'), (4, '11:00-12:00'), (5, '12:00-13:00'), (6, '13:00-14:00'), (7, '14:00-15:00'), (8, '15:00-16:00'), (9, '16:00-17:00'), (10, '17:00-18:00'), (11, '18:00-19:00'), (12, '19:00-20:00'), (13, '20:00-21:00'), (14, '21:00-22:00'), (15, '22:00-23:00')], verbose_name='预约时间'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_room', 'book_date', 'time')},
        ),
    ]
