# Generated by Django 4.1.4 on 2023-04-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_book_book_name_alter_book_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
